artifact_location: file:D:/Projects/mlops_exam/mlflow_tracking/804095861918832998
creation_time: 1780235706252
experiment_id: '804095861918832998'
last_update_time: 1780235706252
lifecycle_stage: active
name: demand_forecast
trace_location: null
workspace: default
